#! /bin/bash
#
# helppara 2.1.0, 2022-10-01, 2022-10-08, 2022-12-15, 2022-12-16
#
# Tries to extract the line from the help page of a program $1 which
# describes the call parameter $2.
#
# Versucht die Zeile aus der Hilfeseite eines Programms $1 zu extrahieren,
# welche den Aufrufparameter $2 beschreibt.
#
# Bernd Storck, https://www.facebook.com/BStLinux/
#

progname="$1"
shift

function getDescription {
  filter="$1"
  [ -z $2 ] && helpParameterStyle="--help" || helpParameterStyle="$2"

  $progname $helpParameterStyle 2>&1 | grep --color=always -E $filter
  wasFound="$?"
  return "$wasFound"
}

# The following if clause for parameter parsing from param 2022-10-09:
if [ "${1:0:1}" = '+' ]; then # 2020-08-11: Erzeugt aus "+ab" " -a -A -b -B"
    paraString="$(tr -s ' ' <<< "$@")"
  # paraString="$(sed 's:^+*::' <<< "$paraString")"
    paraString="${1/+/}"
    # echo "\$paraString = $paraString"
    for ((i=0;i<${#paraString};i++)); do
        capital="${paraString:i:1}"; capital="${capital^^}"
        paraList+=" -${paraString:i:1} -${capital}"
    done
elif [ "${1:0:1}" = ':' ]; then # 2022-10-08: Erzeugt aus ":ab..." " -a -b ..."
    paraString="$(tr -s ' ' <<< "$@")"
    paraString="${1/:/}"
    # echo "\$paraString = $paraString"
    for ((i=0;i<${#paraString};i++)); do
        paraList+=" -${paraString:i:1}"
    done
  else
    paraList="$@"
fi

for i in $paraList;
do
wasFound=-1
  for j in "--help" "-h";
  do
    if [ "$wasFound" -eq 0 ]; then
      break
    fi
    LEN="${#i}"
    if (( LEN > 1 )); then                                          # AUFRUF MIT
      if [ "${i:0:2}" = '--' ]; then
        if ! getDescription "-E \"^\s*\-[a-zA-Z0-9]\b[,;]{,1}\s+${i}\"" "$j"; then  # f.e.: "--count"
          if ! getDescription "^\s*${i}" "$j"; then                                 # f.e.: "ls --full-time"
            getDescription "\-\-${i:2}" "$j"                             # f.e.: "grep --silent"
          fi
        fi
      else
        getDescription "^\s*-${i:1:1}\b" "$j"                            # f.e: "-c"
      fi
    else
      getDescription "^\s*\-${i}\b" "$j"                                 # f.e: "c"
    fi
  done
done
