#! /bin/bash
#
# helppara 2.0.0, 2022-10-01, 2022-10-08, 2022-12-15, 2022-12-16
#
# Versucht die Zeile aus der Hilfeseite eines Programms $1 zu extrahieren,
# welche den Aufrufparameter $2 beschreibt.
#
# Bernd Storck, https://www.facebook.com/BStLinux/
#

progname="$1"
shift

function getDescription {
  filter="$1"
  [ -z $2 ] && helpParameterStyle="--help" || helpParameterStyle="$2"

  $progname $helpParameterStyle 2>&1 | grep --color=always -E $filter
  wasFound="$?"
  return "$wasFound"
}

for i in $@;
do
wasFound=-1
  for j in "--help" "-h";
  do
    if [ "$wasFound" -eq 0 ]; then
      break
    fi
    LEN="${#i}"
    if (( LEN > 1 )); then                                          # AUFRUF MIT
      if [ "${i:0:2}" = '--' ]; then
        if ! getDescription "-E \"^\s*\-[a-zA-Z0-9]\b[,;]{,1}\s+${i}\"" "$j"; then  # f.e.: "--count"
          if ! getDescription "^\s*${i}" "$j"; then                                 # f.e.: "ls --full-time"
            getDescription "\-\-${i:2}" "$j"                             # f.e.: "grep --silent"
          fi
        fi
      else
        getDescription "^\s*-${i:1:1}\b" "$j"                            # f.e: "-c"
      fi
    else
      getDescription "^\s*\-${i}\b" "$j"                                 # f.e: "c"
    fi
  done
done
